import React from "react";
import type {Metadata} from "next";

export const metadata: Metadata = {
  title: "activitiy | thousandtemples",
  description: "Generated by create next app",
};

export default function ActivityLayout ({ children }: { children: React.ReactNode }) {
  return (
    <main className="w-full">
      {children}
    </main>
  )
}