import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import navigations from "@/data/navigations.json";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Header navigations={navigations} />
				<div className='w-full flex justify-center items-center'>
					{children}
				</div>
				<Footer navigations={navigations} />
			</body>
		</html>
	);
}
